name: Build and Test
run-name: ${{ github.actor }} Build and test
on: [push]
jobs:
  build_and_test_ros2:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
      - name: Build and run tests
        uses: ros-tooling/action-ros-ci@0.4.4
        with:
          package-name: cm_executors
          target-ros2-distro: jazzy
